name: cpextra
root: ~/p/cpextra

windows:
  - editor:
      layout: main-vertical
      panes: 
        - vim
          #- gulp test-dev
  - server:
      layout: even-horizontal
      panes:
        - npm run docs:dev
          #- gulp
